# Generated by Django 2.2.7 on 2019-11-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=150)),
                ('contrasena', models.CharField(max_length=256)),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.CharField(max_length=150)),
            ],
        ),
    ]
