# Generated by Django 2.2.7 on 2019-11-15 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_witte'),
    ]

    operations = [
        migrations.AddField(
            model_name='witte',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Usuario'),
        ),
    ]
