# Generated by Django 2.2.7 on 2019-11-13 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=150)),
                ('contrasena', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('imagen', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Witte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=256)),
                ('fecha', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proDjango.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=256)),
                ('fecha', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proDjango.Usuario')),
                ('witte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proDjango.Witte')),
            ],
        ),
    ]
